---
# tasks file for svenagnew.collectd

- name: Install Collectd
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - collectd
    - collectd-utils

- name: Upload a collectd Config files
  template: src=etc/collectd/collectd.conf.j2 dest=/etc/collectd/collectd.conf owner=root group=root mode=0644
  notify: collectd-service-handler
